# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ImagePreviewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
 pod 'GKPhotoBrowser'
 pod 'YYModel'

end
